version: "3.9"

services:
  holiday-back:
    build:
      context: ./holidaykeeper_back
      dockerfile: Dockerfile
    container_name: holiday-back
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod


  holiday-front:
    build:
      context: ./holidaykeeper_front
      dockerfile: Dockerfile
    container_name: holiday-front
    ports:
      - "3000:80"
    depends_on:
      - holiday-back
